apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: sufiyaacr2025.azurecr.io/backend:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: acr-secret